baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Griffin's Profile"
theme: "../.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  favicon: "/images/Wirth_Pic.jpg"
  description: ""

# Navbar Menus
  customMenus:
    - name: "Resume"
      Url: "/Griffin Wirth Resume.pdf"
  


  # home
  disable_home: false
  profile_image: "images/Wirth_Pic.jpg"
  name: "Griffin Wirth"
  namecolor: ffc107
  profession: "Integrative Informatics"
  github: "https://github.com/WirthG"
  email: "mailto:griffiniwirth@gmail.com"
  linkedin: "https://www.linkedin.com/in/griffin-wirth-90647a224" 

  # About
  disable_about: false
  descripe_l1_person: "I am a junior at Allegheny College studying Integrative Informatics with a focus on Media and Visual Production. In this major, I have focused in Data Analytics, Data Abstraction, Electronic/Intermedia Art, Web Design, Digital Storytelling, and Software Design. In addition, during this program, I have learned to program in Python, R, VSCode, CADD, SolidWorks, HTML, and CSS. I have also worked with Adobe Premier, and Adobe Pro as well as operated Panasonic P2 TV studio cameras. Outside of the classroom, I have applied my interest in Visual Production by designing and operating light boards for theatre and dance productions on campus."
  descripe_l2_person: "If you want to find out more about me through my projects, you can find my works [here.](#projects)"
  descripe_l3_person: "If you want to get in touch with me, my email is here." 
  skills:
    - name: Python
      percentage: 65
    - name: R
      percentage: 65
    - name: Windows
      percentage: 85
    - name: Adobe Creative Suite
      percentage: 95
    - name: VSCode
      percentage: 80 
    - name: SolidWorks(CAD)
      percentage: 85


  # Experience
  disable_experience: false
  experience:
    - company: "CMPSC"
      # id: "Computer Science Classes" // use this, when you want to change the id(used for navigation)
      role: "Data Analytics, Data Abstraction, Web Design, Robotics, and SolidWorks."
      startdate: Sep 2020
      enddate: Present
      featuredpoints: 
        - point: Data Analytics - Introduction to explore R Programming, looked at website traffic data with Google Analytics, understanding textual analysis in project papers about data, and more.  
        - point: Data Abstraction - Introduction class using Python for computational constructs and list data structures with odd nods and even nods, Inherence and abstract classes with abstract classes and methods, and more. 
        - point: Web Design - Learned and practiced how to design, implement, and maintenance a mobile-ready web sites. Used HTML and CSS. This website is a product of that class.  
        - point: Robotics - Got to build, program, and use robots like GoPiGO's, Parrot Bebop Drone's, TurtleBot's, and Evo Arm's. At the end of the class we got to show our projects off on campus. I showed off my Evo Arm project, linked down below in my projects.
        - point: SolidWorks - A class on using SolidWork's CADD software to create 3D models of parts. 
    - company: "Other"
      # id: "Other Classes" // use this, when you want to change the id(used for navigation)
      role: " Introduction to Media Culture, Electronic & Intermedia Art, Filmmaking and Digital Story Telling"
      startdate: Sep 2020
      enddate: Dec 2022
      featuredpoints:
        - point: Media Culture Class - Explored the role media plays in our everyday lives and studied the way media participates in the shaping of identities and cultures.
        - point: Electronic & Intermedia Art - Using electronic technologies/software and digital media as art-making tools. Awareness of the elements of 2D design/composition and the vocabulary used to describe it.
        - point: Filmmaking and Digital Story Telling - Studied and preformed the concept of production involved in cinematic and television production. Operated Panasonic P2 TV studio cameras.
    - company: "Internship"
      # id: "Internship" // use this, when you want to change the id(used for navigation)
      role: "None Yet"
      startdate: Feb 2019
      enddate: Jan 2020
      featuredpoints:
        - point: "None"
        - point: "None"

  # Education
  disable_education: false
  education:
    - degree: "Allegheny College"
      branch: "Meadville, PA"
      university: "Integrative Informatics & Theater"
      startedyear: "2020"
      graduation: "2024"
    - degree: "Quaker Valley High School"
      branch: "Leetsdale, PA"
      university: "Introduction into Python"
      startedyear: "2017"
      graduation: "2020"


  # Projects
  disable_projects: false
  projects:
    - name: "Cryptography and Cryptanalysis"
      img: "images/password.jpg"
      githublink: "https://github.com/WirthG/Password_Project"
      featuredlink: ""
      description: "Using Python, River and I coded a project that sends cryptic messages and also decrypts them when a password, acting as a key, is typed. We used a symmetric encryption to lock and unlock the key."
    - name: "EvoArm Block Placement Program"
      img: "images/Evo arm 2.webp"
      githublink: "https://github.com/CMPSC-311-Allegheny-College-Fall-2022/project4-evoarm_3ppl"
      description: "Makell and I used the given EvoArm site and made a program that uses all six motors to picks up three different sized blocks and places them in a container."
    
    - name: "BeBop Drone Program"
      img: "images/BeBop Drone2.webp"
      githublink: "https://github.com/CMPSC-311-Allegheny-College-Fall-2022/project2-bebop-griffin-trang"
      description: "Trang and I programed a Bebop drone to do things like fly forward and do a flip! In the repository there is a folder marked video. In it, there is a link to a short demonstration video of the program working."

    - name: "Portrait Photos"
      img: "/images/Face3.jpg"
      githublink: ""
      featuredlink: "https://docs.google.com/drawings/d/1pzFUqM_dncOIICHalcHs5dZkrEMZy_6t6clOilvaswU/edit?usp=sharing"
      description: "Link to a drawling board of portrait pictures I have taken of my friends and family."

    - name: "Landscape Photos"
      img: "images/Chautqua.jpg"
      githublink: ""
      featuredlink: "https://docs.google.com/drawings/d/1RaYKh2vv1Aa4IrOll_IiXvfDzfbK6rjgTnJC1GbPNTw/edit?usp=sharing"
      description: "Link to a drawling board of my landscape pictures."
    
    - name: "Flower Photos"
      img: "images/Chautqua.jpg"
      githublink: ""
      featuredlink: "https://docs.google.com/drawings/d/1z5hKi0GLCeK3EjPxUK_2wCqmu2EEjB2PFzIobfLKnkc/edit?usp=sharing"
      description: ""
   
    - name: "Architecture Photos"
      img: "images/Chautqua.jpg"
      githublink: ""
      featuredlink: "https://docs.google.com/drawings/d/1RaYKh2vv1Aa4IrOll_IiXvfDzfbK6rjgTnJC1GbPNTw/edit?usp=sharing"
      description: ""
    

  # Photos
  disable_achievements: false
  Photos:
    - title: Portrait
      description: Portrait pictures of my friends and family.
      img: /images/Face.jpg
    - title: Landscape
      description: Landscape pictures of the places I have been.
      img: /images/Land1.jpg
    - title: Flowers
      description: Flower pictures. Most from Phipps Conservatory and Botanical Gardens in Pittsburgh.
      img: /images/Flower.jpg
    - title: Architecture
      description: Architecture pictures of structures that I have taken.
      img: /images/Arch.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you in time!
  email: "griffiniwirth@gmail.com"

  # Footer
  socialiconfooter: true
  recentposts: false

  # Blog
  showdescription: false
  tweet: false
