baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Griffin's Profile"
theme: "../.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  favicon: "/images/Wirth_Pic.jpg"
  description: ""

# Navbar Menus
  customMenus:
    - name: "Resume"
      Url: "/Griffin Wirth Resume.pdf"
  


  # home
  disable_home: false
  profile_image: "images/Wirth_Pic.jpg"
  name: "Griffin Wirth"
  namecolor: ffc107
  profession: "Master of Entertainment Management"
  github: "https://github.com/WirthG"
  email: "mailto:griffiniwirth@gmail.com"
  linkedin: "https://www.linkedin.com/in/griffin-wirth-90647a224" 

  # About
  disable_about: false
  descripe_l1_person: "I'm a graduate student at Carnegie Mellon University, pursuing a Master's degree in Entertainment Management. My passion for film and video game production stems from my undergraduate studies in Media and Visual Production, where I focused on digital art, web design, and film production. Throughout my whole academic journey, I've developed a skill set that spans across various creative and technical fields."
  descripe_l2_person: "My [projects](#projects) section showcases my work in film, computer science, and photography, reflecting my dedication to blending creativity with technology."
  descripe_l3_person: "If you want to get in touch with me, my email is here." 
  skills:
    - name: WordPress
      percentage: 70
    - name: R
      percentage: 90
    - name: Windows
      percentage: 90
    - name: Adobe Creative Suite
      percentage: 95
    - name: VSCode
      percentage: 80 
    - name: SolidWorks(CAD)
      percentage: 85
    - name: Vectorworks Spotlight
      percentage: 95


  # Experience
  disable_experience: false
  experience:
    - company: "PBT"
      # id: "PBT" // use this, when you want to change the id(used for navigation)
      role: "Pittsburgh Ballet Theatre Marketing Internship"
      startdate: October 2024
      enddate: Present
      featuredpoints: 
        - point: Create Blog Posts - I created a blog post, using WordPress, comparing Jorden Morris 2016 versions of Peter Pan and Trey McIntyre 2024 version of Peter Pan. I highted the costumes/set, choreography, and music.
        - point: Edit Home Website - I helped clean up and update Pittsburgh Ballet Theatre's website to stay updated and easy for users and contributors.
    - company: "CMPSC"
      # id: "Computer Science Classes" // use this, when you want to change the id(used for navigation)
      role: "Computer Science Classes"
      startdate: Sep 2020
      enddate: May 2024
      featuredpoints: 
        - point: Data Analytics - Introduction to explore R Programming, looked at website traffic data with Google Analytics, understanding textual analysis in project papers about data, and more.  
        - point: Data Abstraction - Introduction class using Python for computational constructs and list data structures with odd nods and even nods, Inherence and abstract classes with abstract classes and methods, and more. 
        - point: Web Design - Learned and practiced how to design, implement, and maintenance a mobile-ready web sites. Used HTML and CSS. This website is a product of that class.  
        - point: Robotics - Got to build, program, and use robots like GoPiGO's, Parrot Bebop Drone's, TurtleBot's, and Evo Arm's. At the end of the class we got to show our projects off on campus. I showed off my Evo Arm project, linked down below in my projects.
        - point: SolidWorks - A class on using SolidWork's CAD software to create 3D models of parts. 
    - company: "Other"
      # id: "Other Classes" // use this, when you want to change the id(used for navigation)
      role: "Integrated Informatics Classes"
      startdate: Sep 2020
      enddate: Dec 2022
      featuredpoints:
        - point: Media Culture Class - Explored the role media plays in our everyday lives and studied the way media participates in the shaping of identities and cultures.
        - point: Electronic & Intermedia Art - Using electronic technologies/software and digital media as art-making tools. Studied the elements of 2D design/composition and the vocabulary used to describe it.
        - point: Filmmaking and Digital Story Telling - Studied and preformed the concept of production involved in cinematic and television production. Operated Panasonic P2 TV studio cameras.
   

  # Education
  disable_education: false
  education:
    - degree: "CMU/Heinz College"
      branch: "Pittsburgh, PA/North Hollywood LA"
      university: "Master of Entertainment Industry Management"
      startedyear: "2024"
      graduation: "2026"
    - degree: "Allegheny College"
      branch: "Meadville, PA"
      university: "Integrative Informatics & Theater"
      startedyear: "2020"
      graduation: "2024"
    - degree: "Quaker Valley High School"
      branch: "Leetsdale, PA"
      university: "Introduction into Python"
      startedyear: "2017"
      graduation: "2020"


  # Projects
  disable_projects: false
  projects:
    - name: "Senior Project"
      img: "/images/Senior Project picture.PNG"
      githublink: "https://github.com/ReadyResearchers-2023-24/GriffinWirth-Artifact/tree/docs"
      featuredlink: "https://app.gitbook.com/o/ccafznlSoTWEnYlxVrpY/s/6HscC7e71NuTclvdSHxg/"
      description: "Link to my Allegheny Senior Project, learning website for beginners on 'How to Implement Vectorworks Spotlight into your Performance' as well as a GitHub link to my projects repository."

    - name: "Creative Films"
      img: "/images/Film_New.PNG"
      githublink: ""
      featuredlink: "https://www.youtube.com/playlist?list=PLLw_q0f-_QCl2PosZpaBsKt_6GlOLAJRE"
      description: "Link to my YouTube playlist of films I created at Allegheny College."
    
    - name: "Creative Portfolio"
      img: "/images/Photo Book.jpg"
      githublink: ""
      featuredlink: "https://griffin-wirth-creative-portfolio.netlify.app"
      description: "Link to a portfolio website with digital photo book of photos I have taken and edited, digital art projects I have created, and theatre/music performances I have been in."

    - name: "Cryptography and Cryptanalysis"
      img: "images/password.jpg"
      githublink: "https://github.com/WirthG/Password_Project"
      featuredlink: ""
      description: "Using Python, I coded a project that sends cryptic messages and also decrypts them when a password, acting as a key, is typed. We used a symmetric encryption to lock and unlock the key."
    - name: "EvoArm Block Placement Program"
      img: "images/Evo arm 2.webp"
      githublink: "https://github.com/CMPSC-311-Allegheny-College-Fall-2022/project4-evoarm_3ppl"
      description: "I used the given EvoArm site and made a program that uses all six motors to picks up three different sized blocks and places them in a container."
    
    - name: "BeBop Drone Program"
      img: "images/BeBop Drone2.webp"
      githublink: "https://github.com/CMPSC-311-Allegheny-College-Fall-2022/project2-bebop-griffin-trang"
      description: "Trang and I programed a Bebop drone to do things like fly forward and do a flip! In the repository there is a folder marked video. In it, there is a link to a short demonstration video of the program working."

    

    

      
    

  # Photos
  disable_achievements: true
  Photos:
    - title: Portrait
      description: Portrait pictures of my friends and family.
      img: /images/Face.jpg
    - title: Landscape
      description: Landscape pictures of the places I have been.
      img: /images/Land1.jpg
    - title: Flowers
      description: Flower pictures. Most from Phipps Conservatory and Botanical Gardens in Pittsburgh.
      img: /images/Flower.jpg
    - title: Architecture
      description: Architecture pictures of structures that I have taken.
      img: /images/Arch.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you in time!
  email: "griffiniwirth@gmail.com"

  # Footer
  socialiconfooter: true
  recentposts: false

  # Blog
  showdescription: false
  tweet: false
