baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Griffin's Profile"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  favicon: "/images/Wirth_Pic.jpg"
  description: ""

# Navbar Menus
  customMenus:
    - name: "Resume"
      Url: "/Griffin_Wirth_Resume.pdf"
  



  # home
  disable_home: false
  profile_image: "images/Wirth_Pic.jpg"
  name: "Griffin Wirth"
  namecolor: ffc107
  profession: "Integrative Informatics"
  github: "https://github.com/WirthG"
  email: "mailto:griffiniwirth@gmail.com"
  linkedin: "https://linkedin.com" 

  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Griffin and I'm a student at Allegheny College. I am a Integrative Informatics major, with a focus in media and visual production. My extracurriculars include Allegheny College Men's Soccer Team where I practice every day for two hours and play in games every weekend, Allegheny College Symphony where I play baritone saxophone and have a concert at the end of each semester, Allegheny College Men's Ensemble where I sing baritone and also have a concert each semester, Allegheny College Playshop Theatre where I served as stage manager for the play called The Whole Shebang"
  descripe_l2_person: "If you want to find out more about me through my projects, you can find my works [here](#projects)"
  descripe_l3_person: "If you want to get in touch with me, my email is here" 
  skills:
    - name: Python
      percentage: 40
    - name: R
      percentage: 55
    - name: Windows
      percentage: 80
    - name: Adobi Creative Suite
      percentage: 90

  # Experience
  disable_experience: false
  experience:
    - company: "CMPSC"
      # id: "Computer Science Classes" // use this, when you want to change the id(used for navigation)
      role: "Computational Expression, Data Analytics, Data Abstraction"
      startdate: Sep 2020
      enddate: Dec 2021
      featuredpoints: 
        - point: All three classes taken during first and second year.
        - point: Introduction class into Python(Computational Expression & Data Abstraction) and R(Data Analytics).
    - company: "Other"
      # id: "Other Classes" // use this, when you want to change the id(used for navigation)
      role: " Introduction to Media Culture, Electronic & Intermedia Art"
      startdate: Sep 2020
      enddate: Dec 2021
      featuredpoints:
        - point: Media Culture Class - explore the role media play in our everyday lives and study the ways media participate in the shaping of identities and cultures.
        - point: Electronic & Intermedia Art - Using electronic technologies/software and digital media as art-making tools. Awareness of the elements of 2D design/composition and the vocabulary used to describe it.
    - company: "Internship"
      # id: "Internship" // use this, when you want to change the id(used for navigation)
      role: "None Yet"
      startdate: Feb 2019
      enddate: Jan 2020
      featuredpoints:
        - point: "None"
        - point: "None"

  # Education
  disable_education: false
  education:
    - degree: "Allegheny College"
      branch: "Meadville, PA"
      university: "CMPSC and Other listed above"
      startedyear: "2020"
      graduation: "2024"
    - degree: "Quaker Valley High School"
      branch: "Leetsdale, PA"
      university: "Introduction into Python"
      startedyear: "2017"
      graduation: "2020"


  # Projects
  disable_projects: false
  projects:
    - name: "Cryptography and Cryptanalysis "
      img: "images/password.jpg"
      githublink: "https://github.com/WirthG/Password_Project"
      featuredlink: ""
      description: "Using Python my friend and I codded a project that sends criptic messages and also decripts them when a password, acting as a key, is typed. We used a symmetric encryption to lock and unlock the key."

  # Photos
  disable_achievements: false
  Photos:
    - title: Portrait
      description: Prtrait pictures of my friends and family.
      img: /images/achiv.jpg
    - title: Landscape
      description: Landscape pictures of the plaes I have been
      img: /images/achiv.jpg
    - title: Flowers
      description: Flower pictures
      img: /images/achiv.jpg
    - title: Architecture
      description: Architecture pictures of strutures that I have taken
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "griffiniwirth@gmail.com"

  # Footer
  socialiconfooter: true
  recentposts: false

  # Blog
  showdescription: false
  tweet: false
